version: '3'

services:
  web:
    build:
      context: .
      dockerfile: infrastructure/web/Dockerfile
    image: bkuhl/laravel-starter:web
    env_file: .env
    ports:
      - "80:80"
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
